import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// page 밖에 적는 것들을 여기에 적음...head 태그에 넣는거, 상단바 등

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
